services:
  - type: web
    name: free-fire-emote-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
    healthCheckPath: /status
    autoDeploy: true